### ISSUE TITLE
Compiling on ARM

### ISSUE THREAD

**Issue by Reichl** [ulli-kroll/rtl8821au#1]
Tried to compile on odroid C1 (arm), Ubuntu, gcc version 4.8.2 (Ubuntu/Linaro 4.8.2-19ubuntu1).
Linux odroid-c1 3.10.65 #20 SMP PREEMPT Tue Jan 27 09:53:32 CET 2015 armv7l armv7l armv7l GNU/Linux

Had to patch Makefile to compile
--- Makefile.orig       2015-01-27 16:49:39.672914299 +0100
+++ Makefile    2015-01-27 16:50:39.054571482 +0100
@@ -7,6 +7,7 @@
 #EXTRA_CFLAGS += -pedantic
 #EXTRA_CFLAGS += -Wshadow -Wpointer-arith -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes
 
+EXTRA_CFLAGS += -Wno-implicit-function-declaration
 EXTRA_CFLAGS += -Wno-unused-variable
 EXTRA_CFLAGS += -Wno-unused-value
 EXTRA_CFLAGS += -Wno-unused-label
@@ -107,7 +108,7 @@
 
 ifeq ($(CONFIG_PLATFORM_I386_PC), y)
 EXTRA_CFLAGS += -DCONFIG_LITTLE_ENDIAN
-SUBARCH := $(shell uname -m | sed -e s/i.86/i386/)
+SUBARCH := $(shell uname -m | sed -e s/i.86/i386/ | sed -e s/ppc/powerpc/ | sed -e s/armv.l/arm/)
 ARCH ?= $(SUBARCH)
 CROSS_COMPILE ?=
 KVER  := $(shell uname -r)

Got the module but also:
WARNING: "ether_addr_copy" [/usr/src/rtl8821au/rtl8821au.ko] undefined!
Cannot test the module yet, no HW.

**Comment by Reichl** [comment]
Finally got the module:

Makefile:
-SUBARCH := $(shell uname -m | sed -e s/i.86/i386/)
+SUBARCH := $(shell uname -m | sed -e s/i.86/i386/ | sed -e s/ppc/powerpc/ | sed -e s/armv.l/arm/)

os_dep/linux/usb_intf.c:
-       ether_addr_copy(ndev->dev_addr, padapter->eeprompriv.mac_addr);
+       memcpy(ndev->dev_addr, padapter->eeprompriv.mac_addr, ETH_ALEN);

ether_addr_copy seems not yet to exist in kernel 3.10.

**Comment by ulli-kroll** [comment]
Hello,

solved in current git.
And you don't need to rewirte the Makefile.

see most recent README
