### ISSUE TITLE
HAL_DEF_VARIABLE value 14 unhandled

### ISSUE THREAD

**Issue by paralin** [ulli-kroll/rtl8821au#2]
I'm getting the warning:

 rtl8821au: rtl8821au_set_hal_def_var: [ERROR] HAL_DEF_VARIABLE(14) not defined!

I believe this is a case that needs to be handled in the code, there's a switch here: 

https://github.com/austinmarton/rtl8812au_linux/blob/master/hal/hal_com.c#L1227

I can't find it in this repository, though. Not sure where it's coming from. Maybe the firmware?

**Comment by ulli-kroll** [comment]
No, not from the firmware.
The first occurrence may from HW_VAR_ON_RCR_AM somewhere in the core 
(aka ieee80211 lib from Realtek)

The vars are defined in include/hal_intf.h.
These are successive removed by me, due no precence in rtlwifi-lib.

The error messages is original from the driver developers at realtek.
And I don't care about this ...

Hans Ulli
