### ISSUE TITLE
Operation not supported on arm

### ISSUE THREAD

**Issue by paralin** [ulli-kroll/rtl8821au#5]
I'm getting the following errors trying to use wpa_supplicant in wext mode:

```
# journalctl -fu wpa_supplicant@wlan0
-- Logs begin at Sat 2016-05-21 22:31:33 UTC. --
May 21 22:34:48 qr6 wpa_supplicant[539]: wlan0: CTRL-EVENT-SCAN-FAILED ret=-1 retry=1
May 21 22:34:49 qr6 wpa_supplicant[539]: ioctl[SIOCSIWSCAN]: Operation not supported
```

Same in all the other driver modes.

iwconfig returns:

```
wlan0     no wireless extensions.
```

iw list returns:

```
# iw list
# 
```

... nothing

And lsmod:

```
# lsmod
Module                  Size  Used by
ipt_MASQUERADE           874  1
nf_nat_masquerade_ipv4     1901  1 ipt_MASQUERADE
iptable_nat             1490  1
nf_conntrack_ipv4      10843  2
nf_defrag_ipv4          1124  1 nf_conntrack_ipv4
nf_nat_ipv4             4299  1 iptable_nat
xt_addrtype             1551  2
xt_conntrack            2597  1
nf_nat                 10609  2 nf_nat_ipv4,nf_nat_masquerade_ipv4
nf_conntrack           76161  5 nf_nat,nf_nat_ipv4,xt_conntrack,nf_nat_masquerade_ipv4,nf_conntrack_ipv4
br_netfilter           12945  0
aufs                  179515  0
rtl8821au             398147  0
```

`dmesg | grep 8821`

```
# dmesg | grep 8821au
[    6.530141] rtl8821au:_ConfigChipOutEP_8812():<0-0> Tx queue select :0x07..
[    6.734813] usbcore: registered new interface driver rtl8821au
[    8.208796] usb 1-3.1: rtl8821au: hw_init USB-ID 7392:a812 Edimax AC600 USB Realtek HIGH-SPEED 
[    8.294105] Loading firmware rtlwifi/rtl8821aufw.bin
```

Any ideas?

**Comment by ulli-kroll** [comment]
Hi,

Is the driver working anyway ?
Or this is only an annoying bug ?

Please check also the **wireless-ext**.branch.
This is my cleaning branch for cherry pick into rtlwifi

**master** is currently not updated, to maintain it pullable.

**Comment by paralin** [comment]
Doesn't seem to work. I'd love to try wireless-ext.

Will do today.

**Comment by paralin** [comment]
Tried wireless-ext on the latest kernel version and I'm getting the same thing.

iw list is empty, and iwconfig prints "no wireless extensions"

**Comment by ulli-kroll** [comment]
Hi,

I made some tests on laptop running Sabayon Linux/Limbo aka testing
with systemd v226 HW:D-LINK DWA 171
works like a charm

Other HW some Zyxel NSA 325 with Marvell Kirkwood Kernel v4.6.2
Minimal setup only ~8 MIB initramfs with basic tools.
Also OK, I do some of my speed / scripting tests here ...

This error is part of wireless-ext in /core of the driver and this directory
doesn't exist in the **rtlwifi** branch, because it's not needed.any more.

Only /rtl8821au will survive and currently this can't be pushed
-> broken as hell

Ticked closed

**Comment by paralin** [comment]
Well... You haven't suggested how to fix this and I can no longer get your driver working at all so im probably going to just switch to some other fork...

**Comment by brainstorm** [comment]
@paralin Perhaps worth checking out upstream's `rtl8xxx` generic driver? It might substitute Uli Kroll's work in the future:

http://lxr.free-electrons.com/source/drivers/net/wireless/realtek/rtl8xxxu/rtl8xxxu.c

```
  * This driver was written as a replacement for the vendor provided
  * rtl8723au driver. As the Realtek 8xxx chips are very similar in
  * their programming interface, I have started adding support for
  * additional 8xxx chips like the 8192cu, 8188cus, etc.
```

**Comment by ulli-kroll** [comment]
`git grep USB_VENDOR_ID_REALTEK  drivers/net/wireless/realtek/`
does not print any of the 802.11ac WIFI NICs.
Not even the ID's for the demoboards, which some OEMs are using for their product.
Sorry for that.

On the other hand
I have queued one or more patches for upstream, related to usb probe.
Without this my rtlwifi branch will not compile.
