### ISSUE TITLE
Avoid having to re-install drivers on reboot

### ISSUE THREAD

**Issue by birgersp** [ulli-kroll/rtl8821au#9]
As described [here](http://serverfault.com/questions/147501/will-modules-installed-by-insmod-command-persist-after-rebooting), modules installed by insmod won't persist after reboot.

Removed the `installfw` target, added `install` and `uninstall` instead. After install target is run, the drivers can be installed (persisting after reboots) by using

`sudo modprobe rtl8821au`

**Comment by ulli-kroll** [comment]
See comment in pull request
#10

**Comment by birgersp** [comment]
(Wrote this comment in the pull request but I guess it is more appropriate to put it here)

Fair enough. How would you feel about adding instructions on how to "persistently" install this driver in the readme? I think it would be very useful for people who needs this driver, but are beginners to linux

**Comment by birgersp** [comment]
In my personal opinion, the current actions of "installfw" is a bit misleading. Maybe it's just me, but I'd expect "installing" a driver makes it persist over reboots.

I realize it is copying the drivers into the system, so I guess technically it is infact "installing" the drivers. Still, it was confusing to find my drivers disabled after I had rebooted.
